version: '3.2'

networks:
  shared:
    external:
      name: reverseproxy

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        UID: ${USER_ID:-1000}
        GID: ${GROUP_ID:-1000}
    ports:
      - 9001:80
    volumes:
      - .:/app
    networks:
      - default
      - shared

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9002:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eventsauce-dev
    volumes:
      - ./docker/mysql/custom.conf:/etc/mysql/conf.d/custom.conf
      - ./.db-data:/var/lib/mysql

  redis:
    image: redis:6-alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 9003:5672
      - 9004:15672
    volumes:
      - ./.queue-data:/var/lib/rabbitmq/
